### ISSUE TITLE
why when i run npm start error ?

### ISSUE THREAD

**Issue by HanzYiz** [SomnathDas/Whatsapp-Botto-Re#21]
**when i type npm start ti looks like this ?**

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'bent'
Require stack:
- C:\Whatsapp-Botto-Re-master\Whatsapp-Botto-Re-master\msgHandler.js
- C:\Whatsapp-Botto-Re-master\Whatsapp-Botto-Re-master\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Whatsapp-Botto-Re-master\Whatsapp-Botto-Re-master\msgHandler.js:12:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Whatsapp-Botto-Re-master\\Whatsapp-Botto-Re-master\\msgHandler.js',
    'C:\\Whatsapp-Botto-Re-master\\Whatsapp-Botto-Re-master\\index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-botto-re@3.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-botto-re@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**How to solve it?**

**Comment by AlenVelocity** [comment]
You can solve it by using `npm i bent`

This has been fixed in the [Latest Commit](https://github.com/SomnathDas/Whatsapp-Botto-Re/commit/90d0ca797658ecc01ab5d2670aac218dc58483f4)
