### ISSUE TITLE
?

### ISSUE THREAD

**Issue by ben-dev2609** [SomnathDas/Whatsapp-Botto-Re#23]
C:\Users\User\Whatsapp-Botto-Re\msgHandler.js:219
        case 'unban':
        ^^^^

SyntaxError: Unexpected token 'case'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\User\Whatsapp-Botto-Re\index.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-botto-re@3.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-botto-re@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-09-25T04_08_44_283Z-debug.log

**Comment by AlenVelocity** [comment]
This has been fixed in the latest commit
