### ISSUE TITLE
REAL ISSUE HERE

### ISSUE THREAD

**Issue by EthanNoSkill** [SomnathDas/Whatsapp-Botto-Re#24]
Where is the link to buy premium feature

**Comment by EthanNoSkill** [comment]
Error: Failed to launch the browser process! spawn C:\Program Files\Google\Chrome\Application\chrome.exe ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:185:85)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by NaldoMota1** [comment]
bagaimana memperbaiki kesalahan ini

**Comment by AlenVelocity** [comment]
@EthanNoSkill Its fixed, Please use the latest commit and We've now included the previously paid features in in the repo, If you'd like to donate use this [url](https://www.paypal.com/paypalme/EtherealWaifuHub)

**Comment by NaldoMota1** [comment]
the new features didn't appear to me

**Comment by EthanNoSkill** [comment]
THANK YOU
