### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by ben-dev2609** [SomnathDas/Whatsapp-Botto-Re#27]
SyntaxError: Unexpected token 'case'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\User\Whatsapp-Botto-Re\index.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-botto-re@3.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-botto-re@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-09-28T01_58_58_915Z-debug.log

**Comment by AlenVelocity** [comment]
Can you try doing `node inex.js` and show me what id logs?

**Comment by ben-dev2609** [comment]
Error: Cannot find module 'C:\Users\User\Whatsapp-Botto-Re\inex.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by AlenVelocity** [comment]
sorry, index.js

**Comment by ben-dev2609** [comment]
SyntaxError: Unexpected token 'case'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\User\Whatsapp-Botto-Re\index.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

**Comment by AlenVelocity** [comment]
@SomnathDas Please take a look at this

**Comment by SomnathDas** [comment]
at Object. (C:\Users\User\Whatsapp-Botto-Re\index.js:2:20)
focus on this line and check if there's any syntactical mistake

**Comment by ben-dev2609** [comment]
hmmmm

**Comment by Nuser404** [comment]
![image](https://user-images.githubusercontent.com/50760394/95811214-fd12d200-0d3c-11eb-961d-c546e2ce322a.png)
how to regist command is it necessary use whatsapp business?

**Comment by SomnathDas** [comment]
@Nuser404 Read the code properly and modify it by yourself, you can add new command using case
