### ISSUE TITLE
any idea?

### ISSUE THREAD

**Issue by abcasker** [SomnathDas/Whatsapp-Botto-Re#34]
needsToScan -> error Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at C:\dev\WA BOT\Whatsapp-Botto-Re-3.2.0\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (C:\dev\WA BOT\Whatsapp-Botto-Re-3.2.0\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:207:16)
    at ExecutionContext._evaluateInternal (C:\dev\WA BOT\Whatsapp-Botto-Re-3.2.0\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:200:50)
    at ExecutionContext.evaluateHandle (C:\dev\WA BOT\Whatsapp-Botto-Re-3.2.0\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:151:21)
    at WaitTask.rerun (C:\dev\WA BOT\Whatsapp-Botto-Re-3.2.0\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:498:71)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: socket hang ups
    at connResetException (internal/errors.js:617:14)
    at TLSSocket.socketOnEnd (_http_client.js:493:23)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  config: {
    url: 'https://raw.githack.com/open-wa/wa-automate-nodejs/master/patches.json',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.0'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/open-wa/wa-automate-nodejs/master/patches.json',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'raw.githack.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/open-wa/wa-automate-nodejs/master/patches.json'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /open-wa/wa-automate-nodejs/master/patches.json HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.0\r\n' +
        'Host: raw.githack.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/open-wa/wa-automate-nodejs/master/patches.json',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'raw.githack.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://raw.githack.com/open-wa/wa-automate-nodejs/master/patches.json',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

**Comment by abcasker** [comment]
i did the npm i @open-wa/wa-automate@3.0.14 and wait for the patches, and it cames out
