### ISSUE TITLE
help me pls

### ISSUE THREAD

**Issue by lonnykkj** [SomnathDas/Whatsapp-Botto-Re#57]

**Comment by lonnykkj** [comment]
TimeoutError: waiting for target failed: timeout 30000ms exceeded
    at Object.waitWithTimeout (C:\Whatsapp-Botto-Re\node_modules\puppeteer\lib\cjs\puppeteer\common\helper.js:224:26)
    at Browser.waitForTarget (C:\Whatsapp-Botto-Re\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:269:45)
    at ChromeLauncher.launch (C:\Whatsapp-Botto-Re\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:100:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PuppeteerExtra.launch (C:\Whatsapp-Botto-Re\node_modules\puppeteer-extra\dist\index.cjs.js:129:25)

**Comment by AlenVelocity** [comment]
It is caused by your network. Please make sure you have a stable network connection
