### ISSUE TITLE
Error with stickers

### ISSUE THREAD

**Issue by josearg150** [SomnathDas/Whatsapp-Botto-Re#76]
everytime i send a command related to the stickers i get this error message

[ERROR] Error: message is missing critical data needed to download the file.
    at /home/jose/Whatsapp-Botto-Re/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:83:27
    at step (/home/jose/Whatsapp-Botto-Re/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:44:23)
    at Object.next (/home/jose/Whatsapp-Botto-Re/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:25:53)
    at /home/jose/Whatsapp-Botto-Re/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/jose/Whatsapp-Botto-Re/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:15:12)
    at exports.decryptMedia (/home/jose/Whatsapp-Botto-Re/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:67:71)
    at msgHandler (/home/jose/Whatsapp-Botto-Re/msgHandler.js:98:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by SomnathDas** [comment]
We're looking into this. Mostly certainly the problem is either with the code not being compatible with the new version of OPEN-WA.
